SELECT 
    GENDER_FACTOR,
    'SHELLFISH' AS AllergyType,
    SUM(CASE WHEN SHELLFISH_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'FISH' AS AllergyType,
    SUM(CASE WHEN FISH_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'MILK' AS AllergyType,
    SUM(CASE WHEN MILK_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'SOY' AS AllergyType,
    SUM(CASE WHEN SOY_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'EGG' AS AllergyType,
    SUM(CASE WHEN EGG_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'WHEAT' AS AllergyType,
    SUM(CASE WHEN WHEAT_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'PEANUT' AS AllergyType,
    SUM(CASE WHEN PEANUT_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'SESAME' AS AllergyType,
    SUM(CASE WHEN SESAME_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'TREENUT' AS AllergyType,
    SUM(CASE WHEN TREENUT_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'WALNUT' AS AllergyType,
    SUM(CASE WHEN WALNUT_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'PECAN' AS AllergyType,
    SUM(CASE WHEN PECAN_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'PISTACHIO' AS AllergyType,
    SUM(CASE WHEN PISTACH_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'ALMOND' AS AllergyType,
    SUM(CASE WHEN ALMOND_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'BRAZIL' AS AllergyType,
    SUM(CASE WHEN BRAZIL_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'HAZELNUT' AS AllergyType,
    SUM(CASE WHEN HAZELNUT_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR

UNION ALL

SELECT 
    GENDER_FACTOR,
    'CASHEW' AS AllergyType,
    SUM(CASE WHEN CASHEW_ALG_START > 0 THEN 1 ELSE 0 END) AS AllergyCount
FROM foodallergy
GROUP BY GENDER_FACTOR;
