SELECT 
    AVG(AGE_START_YEARS) AS avg_age_to_start_an_allergy
FROM 
    foodallergy
WHERE
    SHELLFISH_ALG_START > 0
    OR FISH_ALG_START > 0
    OR MILK_ALG_START > 0
    OR SOY_ALG_START > 0
    OR EGG_ALG_START > 0
    OR WHEAT_ALG_START > 0
    OR PEANUT_ALG_START > 0
    OR SESAME_ALG_START > 0
    OR TREENUT_ALG_START > 0
    OR WALNUT_ALG_START > 0
    OR PECAN_ALG_START > 0
    OR PISTACH_ALG_START > 0
    OR ALMOND_ALG_START > 0
    OR BRAZIL_ALG_START > 0
    OR HAZELNUT_ALG_START > 0
    OR CASHEW_ALG_START > 0;
