Use Capstone;
SELECT
    'Shellfish Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN SHELLFISH_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Shellfish_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN SHELLFISH_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Shellfish_with_Asthma,
    COUNT(DISTINCT CASE WHEN SHELLFISH_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Shellfish_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Fish Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN FISH_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Fish_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN FISH_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Fish_with_Asthma,
    COUNT(DISTINCT CASE WHEN FISH_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Fish_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Milk Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN MILK_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Milk_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN MILK_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Milk_with_Asthma,
    COUNT(DISTINCT CASE WHEN MILK_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Milk_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Soy Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN SOY_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Soy_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN SOY_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Soy_with_Asthma,
    COUNT(DISTINCT CASE WHEN SOY_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Soy_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Egg Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN EGG_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Egg_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN EGG_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Egg_with_Asthma,
    COUNT(DISTINCT CASE WHEN EGG_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Egg_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Peanut Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN PEANUT_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Peanut_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN PEANUT_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Peanut_with_Asthma,
    COUNT(DISTINCT CASE WHEN PEANUT_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Peanut_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Sesame Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN SESAME_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Sesame_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN SESAME_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Sesame_with_Asthma,
    COUNT(DISTINCT CASE WHEN SESAME_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Sesame_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Tree Nut Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN TREENUT_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS TreeNut_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN TREENUT_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS TreeNut_with_Asthma,
    COUNT(DISTINCT CASE WHEN TREENUT_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS TreeNut_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Walnut Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN WALNUT_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Walnut_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN WALNUT_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Walnut_with_Asthma,
    COUNT(DISTINCT CASE WHEN WALNUT_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Walnut_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Pecan Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN PECAN_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Pecan_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN PECAN_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Pecan_with_Asthma,
    COUNT(DISTINCT CASE WHEN PECAN_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Pecan_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Pistachio Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN PISTACH_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Pistachio_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN PISTACH_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Pistachio_with_Asthma,
    COUNT(DISTINCT CASE WHEN PISTACH_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Pistachio_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Almond Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN ALMOND_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Almond_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN ALMOND_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Almond_with_Asthma,
    COUNT(DISTINCT CASE WHEN ALMOND_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Almond_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Brazil Nut Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN BRAZIL_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS BrazilNut_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN BRAZIL_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS BrazilNut_with_Asthma,
    COUNT(DISTINCT CASE WHEN BRAZIL_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS BrazilNut_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Hazelnut Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN HAZELNUT_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Hazelnut_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN HAZELNUT_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Hazelnut_with_Asthma,
    COUNT(DISTINCT CASE WHEN HAZELNUT_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Hazelnut_with_Allergic_Rhinitis
FROM foodallergy

UNION ALL

SELECT
    'Cashew Allergy' AS AllergyType,
    COUNT(DISTINCT CASE WHEN CASHEW_ALG_START > 0 AND ATOPIC_DERM_START > 0 THEN SUBJECT_ID END) AS Cashew_with_Atopic_Dermatitis,
    COUNT(DISTINCT CASE WHEN CASHEW_ALG_START > 0 AND ASTHMA_START > 0 THEN SUBJECT_ID END) AS Cashew_with_Asthma,
    COUNT(DISTINCT CASE WHEN CASHEW_ALG_START > 0 AND ALLERGIC_RHINITIS_START > 0 THEN SUBJECT_ID END) AS Cashew_with_Allergic_Rhinitis
FROM foodallergy;
