SELECT 
    (COUNT(DISTINCT CASE WHEN 
        (CASE WHEN SHELLFISH_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN FISH_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN MILK_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN SOY_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN EGG_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN WHEAT_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN PEANUT_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN SESAME_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN TREENUT_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN WALNUT_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN PECAN_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN PISTACH_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN ALMOND_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN BRAZIL_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN HAZELNUT_ALG_START > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN CASHEW_ALG_START > 0 THEN 1 ELSE 0 END)
    > 1 THEN SUBJECT_ID END) * 100.0) / 
    COUNT(DISTINCT SUBJECT_ID) AS percent_multiple_allergies
FROM foodallergy;
