USE `capstone`;
SET SQL_SAFE_UPDATES = 0;

-- Script transformas all columns to more readable format int->string " x years and x months"
-- "alg_start" = age of onset or first recorded case , "alg_end" = age at last recorded case

ALTER TABLE foodallergy
MODIFY COLUMN SHELLFISH_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET SHELLFISH_ALG_START = CONCAT(FLOOR(SHELLFISH_ALG_START), ' yrs and ', ROUND((SHELLFISH_ALG_START - FLOOR(SHELLFISH_ALG_START)) * 12), ' months') Where SHELLFISH_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN SHELLFISH_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET SHELLFISH_ALG_END = CONCAT(FLOOR(SHELLFISH_ALG_END), ' yrs and ', ROUND((SHELLFISH_ALG_END - FLOOR(SHELLFISH_ALG_END)) * 12), ' months') Where SHELLFISH_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN FISH_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET FISH_ALG_START = CONCAT(FLOOR(FISH_ALG_START), ' yrs and ', ROUND((FISH_ALG_START - FLOOR(FISH_ALG_START)) * 12), ' months') Where FISH_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN FISH_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET FISH_ALG_END = CONCAT(FLOOR(FISH_ALG_END), ' yrs and ', ROUND((FISH_ALG_END - FLOOR(FISH_ALG_END)) * 12), ' months') Where FISH_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN MILK_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET MILK_ALG_START = CONCAT(FLOOR(MILK_ALG_START), ' yrs and ', ROUND((MILK_ALG_START - FLOOR(MILK_ALG_START)) * 12), ' months') Where MILK_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN MILK_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET MILK_ALG_END = CONCAT(FLOOR(MILK_ALG_END), ' yrs and ', ROUND((MILK_ALG_END - FLOOR(MILK_ALG_END)) * 12), ' months') Where MILK_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN SOY_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET SOY_ALG_START = CONCAT(FLOOR(SOY_ALG_START), ' yrs and ', ROUND((SOY_ALG_START - FLOOR(SOY_ALG_START)) * 12), ' months') Where SOY_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN SOY_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET SOY_ALG_END = CONCAT(FLOOR(SOY_ALG_END), ' yrs and ', ROUND((SOY_ALG_END - FLOOR(SOY_ALG_END)) * 12), ' months') Where SOY_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN EGG_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET EGG_ALG_START = CONCAT(FLOOR(EGG_ALG_START), ' yrs and ', ROUND((EGG_ALG_START - FLOOR(EGG_ALG_START)) * 12), ' months') Where EGG_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN EGG_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET EGG_ALG_END = CONCAT(FLOOR(EGG_ALG_END), ' yrs and ', ROUND((EGG_ALG_END - FLOOR(EGG_ALG_END)) * 12), ' months') Where EGG_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN WHEAT_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET WHEAT_ALG_START = CONCAT(FLOOR(WHEAT_ALG_START), ' yrs and ', ROUND((WHEAT_ALG_START - FLOOR(WHEAT_ALG_START)) * 12), ' months') Where WHEAT_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN WHEAT_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET WHEAT_ALG_END = CONCAT(FLOOR(WHEAT_ALG_END), ' yrs and ', ROUND((WHEAT_ALG_END - FLOOR(WHEAT_ALG_END)) * 12), ' months') Where WHEAT_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN PEANUT_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET PEANUT_ALG_START = CONCAT(FLOOR(PEANUT_ALG_START), ' yrs and ', ROUND((PEANUT_ALG_START - FLOOR(PEANUT_ALG_START)) * 12), ' months') Where PEANUT_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN PEANUT_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET PEANUT_ALG_END = CONCAT(FLOOR(PEANUT_ALG_END), ' yrs and ', ROUND((PEANUT_ALG_END - FLOOR(PEANUT_ALG_END)) * 12), ' months') Where PEANUT_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN SESAME_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET SESAME_ALG_START = CONCAT(FLOOR(SESAME_ALG_START), ' yrs and ', ROUND((SESAME_ALG_START - FLOOR(SESAME_ALG_START)) * 12), ' months') Where SESAME_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN SESAME_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET SESAME_ALG_END = CONCAT(FLOOR(SESAME_ALG_END), ' yrs and ', ROUND((SESAME_ALG_END - FLOOR(SESAME_ALG_END)) * 12), ' months') Where SESAME_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN TREENUT_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET TREENUT_ALG_START = CONCAT(FLOOR(TREENUT_ALG_START), ' yrs and ', ROUND((TREENUT_ALG_START - FLOOR(TREENUT_ALG_START)) * 12), ' months') Where TREENUT_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN TREENUT_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET TREENUT_ALG_END = CONCAT(FLOOR(TREENUT_ALG_END), ' yrs and ', ROUND((TREENUT_ALG_END - FLOOR(TREENUT_ALG_END)) * 12), ' months') Where TREENUT_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN WALNUT_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET WALNUT_ALG_START = CONCAT(FLOOR(WALNUT_ALG_START), ' yrs and ', ROUND((WALNUT_ALG_START - FLOOR(WALNUT_ALG_START)) * 12), ' months') Where WALNUT_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN WALNUT_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET WALNUT_ALG_END = CONCAT(FLOOR(WALNUT_ALG_END), ' yrs and ', ROUND((WALNUT_ALG_END - FLOOR(WALNUT_ALG_END)) * 12), ' months') Where WALNUT_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN PECAN_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET PECAN_ALG_START = CONCAT(FLOOR(PECAN_ALG_START), ' yrs and ', ROUND((PECAN_ALG_START - FLOOR(PECAN_ALG_START)) * 12), ' months') Where PECAN_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN PECAN_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET PECAN_ALG_END = CONCAT(FLOOR(PECAN_ALG_END), ' yrs and ', ROUND((PECAN_ALG_END - FLOOR(PECAN_ALG_END)) * 12), ' months') Where PECAN_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN PISTACH_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET PISTACH_ALG_START = CONCAT(FLOOR(PISTACH_ALG_START), ' yrs and ', ROUND((PISTACH_ALG_START - FLOOR(PISTACH_ALG_START)) * 12), ' months') Where PISTACH_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN PISTACH_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET PISTACH_ALG_END = CONCAT(FLOOR(PISTACH_ALG_END), ' yrs and ', ROUND((PISTACH_ALG_END - FLOOR(PISTACH_ALG_END)) * 12), ' months') Where PISTACH_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN ALMOND_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET ALMOND_ALG_START = CONCAT(FLOOR(ALMOND_ALG_START), ' yrs and ', ROUND((ALMOND_ALG_START - FLOOR(ALMOND_ALG_START)) * 12), ' months') Where ALMOND_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN ALMOND_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET ALMOND_ALG_END = CONCAT(FLOOR(ALMOND_ALG_END), ' yrs and ', ROUND((ALMOND_ALG_END - FLOOR(ALMOND_ALG_END)) * 12), ' months') Where ALMOND_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN BRAZIL_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET BRAZIL_ALG_START = CONCAT(FLOOR(BRAZIL_ALG_START), ' yrs and ', ROUND((BRAZIL_ALG_START - FLOOR(BRAZIL_ALG_START)) * 12), ' months') Where BRAZIL_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN BRAZIL_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET BRAZIL_ALG_END = CONCAT(FLOOR(BRAZIL_ALG_END), ' yrs and ', ROUND((BRAZIL_ALG_END - FLOOR(BRAZIL_ALG_END)) * 12), ' months') Where BRAZIL_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN HAZELNUT_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET HAZELNUT_ALG_START = CONCAT(FLOOR(HAZELNUT_ALG_START), ' yrs and ', ROUND((HAZELNUT_ALG_START - FLOOR(HAZELNUT_ALG_START)) * 12), ' months') Where HAZELNUT_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN HAZELNUT_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET HAZELNUT_ALG_END = CONCAT(FLOOR(HAZELNUT_ALG_END), ' yrs and ', ROUND((HAZELNUT_ALG_END - FLOOR(HAZELNUT_ALG_END)) * 12), ' months') Where HAZELNUT_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN CASHEW_ALG_START VARCHAR(50);
UPDATE `foodallergy`
SET CASHEW_ALG_START = CONCAT(FLOOR(CASHEW_ALG_START), ' yrs and ', ROUND((CASHEW_ALG_START - FLOOR(CASHEW_ALG_START)) * 12), ' months') Where CASHEW_ALG_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN CASHEW_ALG_END VARCHAR(50);
UPDATE `foodallergy`
SET CASHEW_ALG_END = CONCAT(FLOOR(CASHEW_ALG_END), ' yrs and ', ROUND((CASHEW_ALG_END - FLOOR(CASHEW_ALG_END)) * 12), ' months') Where CASHEW_ALG_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN ATOPIC_DERM_START VARCHAR(50);
UPDATE `foodallergy`
SET ATOPIC_DERM_START = CONCAT(FLOOR(ATOPIC_DERM_START), ' yrs and ', ROUND((ATOPIC_DERM_START - FLOOR(ATOPIC_DERM_START)) * 12), ' months') Where ATOPIC_DERM_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN ATOPIC_DERM_END VARCHAR(50);
UPDATE `foodallergy`
SET ATOPIC_DERM_END = CONCAT(FLOOR(ATOPIC_DERM_END), ' yrs and ', ROUND((ATOPIC_DERM_END - FLOOR(ATOPIC_DERM_END)) * 12), ' months') Where ATOPIC_DERM_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN ALLERGIC_RHINITIS_START VARCHAR(50);
UPDATE `foodallergy`
SET ALLERGIC_RHINITIS_START = CONCAT(FLOOR(ALLERGIC_RHINITIS_START), ' yrs and ', ROUND((ALLERGIC_RHINITIS_START - FLOOR(ALLERGIC_RHINITIS_START)) * 12), ' months') Where ALLERGIC_RHINITIS_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN ALLERGIC_RHINITIS_END VARCHAR(50);
UPDATE `foodallergy`
SET ALLERGIC_RHINITIS_END = CONCAT(FLOOR(ALLERGIC_RHINITIS_END), ' yrs and ', ROUND((ALLERGIC_RHINITIS_END - FLOOR(ALLERGIC_RHINITIS_END)) * 12), ' months') Where ALLERGIC_RHINITIS_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN ASTHMA_START VARCHAR(50);
UPDATE `foodallergy`
SET ASTHMA_START = CONCAT(FLOOR(ASTHMA_START), ' yrs and ', ROUND((ASTHMA_START - FLOOR(ASTHMA_START)) * 12), ' months') Where ASTHMA_START > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN ASTHMA_END VARCHAR(50);
UPDATE `foodallergy`
SET ASTHMA_END = CONCAT(FLOOR(ASTHMA_END), ' yrs and ', ROUND((ASTHMA_END - FLOOR(ASTHMA_END)) * 12), ' months') Where ASTHMA_END > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN FIRST_ASTHMARX VARCHAR(50);
UPDATE `foodallergy`
SET FIRST_ASTHMARX = CONCAT(FLOOR(FIRST_ASTHMARX), ' yrs and ', ROUND((FIRST_ASTHMARX - FLOOR(FIRST_ASTHMARX)) * 12), ' months') Where FIRST_ASTHMARX > 0; 

ALTER TABLE foodallergy
MODIFY COLUMN LAST_ASTHMARX VARCHAR(50);
UPDATE `foodallergy`
SET LAST_ASTHMARX = CONCAT(FLOOR(LAST_ASTHMARX), ' yrs and ', ROUND((LAST_ASTHMARX - FLOOR(LAST_ASTHMARX)) * 12), ' months') Where LAST_ASTHMARX > 0; 





















